### ISSUE TITLE
Can't access CottonMC/StaticData through the maven repository

### ISSUE THREAD

**Issue by Fulmineo64** [CottonMC/StaticData#3]
Hello, 
thank you for making this library, it helped a lot with my datapacks in the Companion Bats mod.

In the last month though I can't seem to access it anymore through the usual repo:
`http://server.bbkr.space:8081/artifactory/libs-release`

I've checked on the server and this path unfortunately doesn't exist anymore.
`http://server.bbkr.space:8081/artifactory/libs-release/io/github/cottonmc/StaticData/1.1.2/StaticData-1.1.2.pom`

Could you please provide me with a new repo for this project?
Thank you very much.

**Comment by Fulmineo64** [comment]
For anyone that may have this issue, i've found a mirror that solves the problem
`https://alexiil.uk/mirrors/server.bbkr.space/maven/`

**Comment by falkreon** [comment]
The mirror is a good plan for current versions. Please be advised that "modern" StaticData is over at https://github.com/DebuggyTeam/StaticData - this is the one that's currently supported, available through modrinth maven, and kept relatively up-to-date. If you have any problems with that version feel free to drop an Issue in over there too!
